// rAthena msg_athena.conf
// 문자 서버의 메시지 구성
// -----------------------
0: 초보자
1: 검사
2: 마술사
3: 궁수
4: 시종
5: 상인
6: 도둑
7: 기사
8: 사제
9: 마법사
10: 대장장이
11: 헌터
12: 암살자
13: 십자군
14: 승려
15: 세이지
16: 로그
17: 연금술사
18: 바드
19: 댄서
20: 결혼식
21: 슈퍼 초보자
22: 건슬링어
23: 닌자
24: 크리스마스
25: 초급
26: 고검객
27: 하이 매지션
28: 하이 아처
29: 고위 사제
30: 고위 상인
31: 고위 도둑
32: 기사
33: 대제사장
34: 하이 위자드
35: 화이트스미스
//35: 마스터스미스 //IRO 이름
36: 스나이퍼
37: 암살자의 십자가
38: 팔라딘
39: 챔피언
40: 교수
//40: 학자 //IRO 이름
41: 스토커
42: 창조자
//42: 생화학자 //IRO 이름
43: 광대
//43: 음유시인 //IRO 이름
44: 집시
45: 초보
46: 아기 검사
47: 아기 마술사
48: 아기 궁수
49: 아기 시종
50: 베이비 머천트
51: 아기 도둑
52: 베이비 나이트
53: 아기 사제
54: 아기 마법사
55: 아기 대장장이
56: 베이비 헌터
57: 아기 암살자
58: 아기 십자군
59: 아기 승려
60: 베이비 세이지
61: 베이비 로그
62: 아기 연금술사
63: 베이비 바드
64: 베이비 댄서
65: 슈퍼 베이비
66: 태권
67: 스타 글래디에이터
68: 소울 링커
//79: 무료
//70: 무료
71: 여름
72: 강시
73: 죽음의 기사
74: 다크 컬렉터
75: 룬 나이트
76: 마법사
77: 레인저
78: 대주교
79: 정비공
80: 단두대 십자가
81: 왕실 근위병
82: 마법사
83: 음유시인
//83: 마에스트로 //IRO 이름
84: 방랑자
85: 수라
86: 유전학
//86: 유전학자 //IRO 이름
87: 섀도우 체이서
88: 베이비 룬 나이트
89: 베이비 워록
90: 베이비 레인저
91: 아기 대주교
92: 베이비 메카닉
93: 베이비 길로틴 크로스
94: 아기 왕실 근위병
95: 아기 마법사
96: 아기 음유시인
97: 아기 방랑자
98: 아기 수라
99: 아기 유전학
100: 아기 그림자 추적자
101: 확장된 슈퍼 초보자
102: 확장된 슈퍼 베이비
103: 카게로
104: 오보로
105: 한복
106: 반란
107: 옥토버페스트
108: 소환사
109: 아기 소환사
110: 베이비 닌자
111: 베이비 카게로
112: 베이비 오보로
113: 아기 태권도
114: 베이비 스타 글래디에이터
115: 베이비 소울 링커
116: 아기 총잡이
117: 아기의 반항
118: 별의 황제
119: 영혼 사신
120: 아기 별황제
121: 아기 영혼 사신
122: 드래곤 나이트
123: 마이스터
124: 섀도우 크로스
125: 대마법사
126: 추기경
127: 윈드호크
128: 제국 근위대
129: 생물학
130: 심연 추적자
131: 원소 마스터
132: 심문관
133: 음유시인
134: 트루베르
135: 하늘 황제
136: 영혼의 금욕주의자
137: 신키로
138: 시라누이
139: 야경
140: 하이퍼 노비스
141: 영혼 조련사

199: 알 수 없는 직업

//경매
200: 경매 관리자
201: 경매
202: 감사합니다, 경매에서 낙찰되셨습니다!
203: 경매 대금 결제!
204: 귀하의 경매에 대한 구매자가 없습니다.
205: 경매가 취소되었습니다.
206: 경매가 종료되었습니다.
207: 경매 낙찰자.
208: 누군가 더 높은 가격으로 입찰했습니다.
209: 더 높은 금액을 입찰하셨습니다.
210: 당신이 경매에서 낙찰되었습니다.
211: 경매 대금 결제!

// @accountinfo
212: 검색 조건 '%s'에 맞는 결과가 없습니다.
213: 오류가 발생했습니다. 관리자에게 문의하십시오.
214: 검색 결과로 %d개의 결과가 반환되었습니다. 더 구체적으로 검색해 주세요...
215: [AID: %d] %s | %s | 레벨: %d/%d | %s
216: ID가 '%d'인 계정을 찾을 수 없습니다.
217: -- 계정 %d --
218: 사용자: %s | GM 그룹: %d | 상태: %d
//219: 무료
//220: 무료
221: 계정 이메일: %s | 생년월일: %s
222: 마지막 IP: %s (%s)
223: 이 사용자는 %d번 로그인했으며, 마지막 로그인 시간은 %s입니다.
224: -- 캐릭터 세부 정보 --
225: [슬롯/CID: %d/%d] %s | %s | 레벨: %d/%d | %s
226: 이 계정에는 문자가 없습니다.

// 업적
227: GM
228: 업적 보상 메일
229: [%s] 업적 보상.