// rAthena msg_athena.conf
// 로그인 서버의 메시지 구성
// -----------------------
0: 미등록 ID.
1: 비밀번호가 잘못되었습니다.
2: 계정이 만료되었습니다.
3: 서버에서 거부되었습니다.
4: GM에게 차단당했습니다.
5: 최신 게임 실행 파일이 아닙니다.
6: 금지됨.
7: 서버 과부하.
8: 회사에서 정한 계좌 한도
9: DBA에 의한 금지
10: 이메일이 확인되지 않았습니다
11: GM에 의한 밴
12: 데이터베이스 작업
13: 셀프 잠금
14: 허용되지 않는 그룹
15: 허용되지 않는 그룹
16: 계정이 삭제되었습니다.
17: 로그인 정보가 남아 있습니다.
18: 해킹 수사.
19: 버그 조사.
20: 문자 삭제.
21: 배우자 캐릭터 삭제
22: 알 수 없는 오류.
