-- NEED equipment build sharing: immutable snapshots, review, public browsing, and owner cancellation.

CREATE TABLE IF NOT EXISTS `need_equipment_build` (
  `build_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `account_id` int unsigned NOT NULL,
  `char_id` int unsigned NOT NULL,
  `char_name` varchar(30) NOT NULL,
  `job_id` smallint unsigned NOT NULL,
  `base_level` smallint unsigned NOT NULL,
  `job_level` smallint unsigned NOT NULL,
  `str` smallint unsigned NOT NULL,
  `agi` smallint unsigned NOT NULL,
  `vit` smallint unsigned NOT NULL,
  `int` smallint unsigned NOT NULL,
  `dex` smallint unsigned NOT NULL,
  `luk` smallint unsigned NOT NULL,
  `category` tinyint unsigned NOT NULL,
  `title` varchar(30) NOT NULL,
  `description` varchar(200) NOT NULL DEFAULT '',
  `status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0=pending,1=approved,2=rejected,3=admin_deleted,4=owner_cancelled',
  `like_count` int unsigned NOT NULL DEFAULT 0,
  `snapshot_hash` char(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approved_at` datetime NULL DEFAULT NULL,
  `approved_by` int unsigned NULL DEFAULT NULL,
  `deleted_at` datetime NULL DEFAULT NULL,
  `deleted_by` int unsigned NULL DEFAULT NULL,
  `review_reason` varchar(200) NULL DEFAULT NULL,
  `delete_reason` varchar(200) NULL DEFAULT NULL,
  `cancelled_at` datetime NULL DEFAULT NULL,
  `reward_eligible` tinyint unsigned NOT NULL DEFAULT 0,
  `reward_item_id` int unsigned NOT NULL DEFAULT 0,
  `reward_amount` int unsigned NOT NULL DEFAULT 0,
  `reward_claimed` tinyint unsigned NOT NULL DEFAULT 0,
  `reward_claimed_at` datetime NULL DEFAULT NULL,
  `reward_approved_by` int unsigned NULL DEFAULT NULL,
  `reward_claim_status` tinyint unsigned NOT NULL DEFAULT 0 COMMENT '0=unclaimed,1=processing,2=completed',
  `reward_claim_started_at` datetime NULL DEFAULT NULL,
  PRIMARY KEY (`build_id`),
  KEY `idx_need_build_char_status` (`char_id`,`status`),
  KEY `idx_need_build_account_status` (`account_id`,`status`),
  KEY `idx_need_build_owner_list` (`account_id`,`char_id`,`build_id`),
  KEY `idx_need_build_admin_char_name` (`char_name`,`build_id`),
  KEY `idx_need_build_account_snapshot` (`account_id`,`snapshot_hash`,`status`),
  KEY `idx_need_build_status_created` (`status`,`created_at`),
  KEY `idx_need_build_reward_claim` (`account_id`,`char_id`,`status`,`reward_eligible`,`reward_claimed`,`reward_claim_status`,`build_id`),
  KEY `idx_need_build_public_likes` (`status`,`job_id`,`category`,`like_count`,`approved_at`,`build_id`),
  KEY `idx_need_build_public_latest` (`status`,`job_id`,`category`,`approved_at`,`build_id`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

CREATE TABLE IF NOT EXISTS `need_equipment_build_like` (
  `like_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `build_id` bigint unsigned NOT NULL,
  `account_id` int unsigned NOT NULL,
  `char_id` int unsigned NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`like_id`),
  UNIQUE KEY `uq_need_build_like_build_account` (`build_id`,`account_id`),
  KEY `idx_need_build_like_account` (`account_id`),
  CONSTRAINT `fk_need_build_like_build` FOREIGN KEY (`build_id`) REFERENCES `need_equipment_build` (`build_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

CREATE TABLE IF NOT EXISTS `need_equipment_build_item` (
  `build_item_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `build_id` bigint unsigned NOT NULL,
  `equip_position` int unsigned NOT NULL,
  `inventory_index` smallint NOT NULL,
  `item_id` int unsigned NOT NULL,
  `refine` tinyint unsigned NOT NULL DEFAULT 0,
  `grade` tinyint unsigned NOT NULL DEFAULT 0,
  `attribute` tinyint unsigned NOT NULL DEFAULT 0,
  `identify` tinyint unsigned NOT NULL DEFAULT 0,
  `card_0` int unsigned NOT NULL DEFAULT 0,
  `card_1` int unsigned NOT NULL DEFAULT 0,
  `card_2` int unsigned NOT NULL DEFAULT 0,
  `card_3` int unsigned NOT NULL DEFAULT 0,
  `random_option_0` smallint NOT NULL DEFAULT 0,
  `random_option_value_0` smallint NOT NULL DEFAULT 0,
  `random_option_param_0` tinyint NOT NULL DEFAULT 0,
  `random_option_1` smallint NOT NULL DEFAULT 0,
  `random_option_value_1` smallint NOT NULL DEFAULT 0,
  `random_option_param_1` tinyint NOT NULL DEFAULT 0,
  `random_option_2` smallint NOT NULL DEFAULT 0,
  `random_option_value_2` smallint NOT NULL DEFAULT 0,
  `random_option_param_2` tinyint NOT NULL DEFAULT 0,
  `random_option_3` smallint NOT NULL DEFAULT 0,
  `random_option_value_3` smallint NOT NULL DEFAULT 0,
  `random_option_param_3` tinyint NOT NULL DEFAULT 0,
  `random_option_4` smallint NOT NULL DEFAULT 0,
  `random_option_value_4` smallint NOT NULL DEFAULT 0,
  `random_option_param_4` tinyint NOT NULL DEFAULT 0,
  PRIMARY KEY (`build_item_id`),
  KEY `idx_need_build_item_build_position` (`build_id`,`equip_position`),
  CONSTRAINT `fk_need_build_item_build` FOREIGN KEY (`build_id`) REFERENCES `need_equipment_build` (`build_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

CREATE TABLE IF NOT EXISTS `need_equipment_build_admin_log` (
  `log_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `build_id` bigint unsigned NOT NULL,
  `admin_account_id` int unsigned NOT NULL,
  `admin_char_id` int unsigned NOT NULL,
  `action` varchar(30) NOT NULL,
  `reason` varchar(200) NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`log_id`),
  KEY `idx_need_build_admin_log_build` (`build_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;

CREATE TABLE IF NOT EXISTS `need_equipment_build_reward_log` (
  `reward_log_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `build_id` bigint unsigned NOT NULL,
  `account_id` int unsigned NOT NULL,
  `char_id` int unsigned NOT NULL,
  `reward_item_id` int unsigned NOT NULL,
  `reward_amount` int unsigned NOT NULL,
  `claimed_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`reward_log_id`),
  UNIQUE KEY `uq_need_build_reward_build` (`build_id`),
  KEY `idx_need_build_reward_account` (`account_id`,`claimed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=euckr COLLATE=euckr_korean_ci;
