
CREATE TABLE IF NOT EXISTS `skill_copyable` (
  `skill_id` INT NOT NULL,
  `skill_code` VARCHAR(50) NOT NULL,
  `skill_name` VARCHAR(100) NOT NULL,
  `job_group` VARCHAR(50) NOT NULL,
  `plagiarism` TINYINT(1) DEFAULT 0,
  `reproduce` TINYINT(1) DEFAULT 0,
  PRIMARY KEY (`skill_id`)
);

TRUNCATE TABLE skill_copyable;
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (5, 'SM_BASH', '배쉬', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (7, 'SM_MAGNUM', '매그넘 브레이크', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (11, 'MG_NAPALMBEAT', '네이팜 비트', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (13, 'MG_SOULSTRIKE', '소울 스트라이크', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (14, 'MG_COLDBOLT', '콜드볼트', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (15, 'MG_FROSTDIVER', '프로스트 다이버', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (17, 'MG_FIREBALL', '화이어 볼', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (18, 'MG_FIREWALL', '화이어 월', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (19, 'MG_FIREBOLT', '화이어 볼트', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (20, 'MG_LIGHTNINGBOLT', '라이트닝 볼트', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (21, 'MG_THUNDERSTORM', '선더스톰', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (24, 'AL_RUWACH', '루아흐', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (28, 'AL_HEAL', '힐', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (42, 'MC_MAMMONITE', '매머나이트', 'Merchant', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (46, 'AC_DOUBLE', '더블 스트레이핑', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (47, 'AC_SHOWER', '애로우 샤워', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (52, 'TF_POISON', '인베넘', 'Thief', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (54, 'ALL_RESURRECTION', '리저렉션', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (62, 'KN_BOWLINGBASH', '볼링 배쉬', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (68, 'PR_ASPERSIO', '아스페르시오', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (69, 'PR_BENEDICTIO', '성체강복', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (70, 'PR_SANCTUARY', '생츄어리', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (77, 'PR_TURNUNDEAD', '턴 언데드', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (79, 'PR_MAGNUS', '마그누스 엑소르시스무스', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (80, 'WZ_FIREPILLAR', '화이어 필라', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (81, 'WZ_SIGHTRASHER', '사이트래셔', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (83, 'WZ_METEOR', '메테오 스톰', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (84, 'WZ_JUPITEL', '유피텔 선더', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (85, 'WZ_VERMILION', '로드 오브 버밀리온', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (86, 'WZ_WATERBALL', '워터볼', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (88, 'WZ_FROSTNOVA', '프로스트 노바', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (89, 'WZ_STORMGUST', '스톰 가스트', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (90, 'WZ_EARTHSPIKE', '어스 스파이크', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (91, 'WZ_HEAVENDRIVE', '헤븐즈 드라이브', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (116, 'HT_LANDMINE', '랜드 마인', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (121, 'HT_FREEZINGTRAP', '프리징 트랩', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (122, 'HT_BLASTMINE', '블래스트 마인', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (123, 'HT_CLAYMORETRAP', '크레모어 트랩', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (141, 'AS_SPLASHER', '베넘 스플래셔', 'Thief', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (148, 'AC_CHARGEARROW', '챠지 애로우', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (152, 'TF_THROWSTONE', '돌 던지기', 'Thief', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (156, 'AL_HOLYLIGHT', '홀리 라이트', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (212, 'RG_BACKSTAP', '백 스탭', 'Thief', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (229, 'AM_DEMONSTRATION', '데몬스트레이션', 'Merchant', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (230, 'AM_ACIDTERROR', '애시드 테러', 'Merchant', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (250, 'CR_SHIELDCHARGE', '쉴드 챠지', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (251, 'CR_SHIELDBOOMERANG', '쉴드 부메랑', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (253, 'CR_HOLYCROSS', '홀리 크로스', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (254, 'CR_GRANDCROSS', '그랜드 크로스', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (263, 'MO_TRIPLEATTACK', '육합권', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (266, 'MO_INVESTIGATE', '침투경', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (267, 'MO_FINGEROFFENSIVE', '탄지신통', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (271, 'MO_EXTREMITYFIST', '아수라 패황권', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (272, 'MO_CHAINCOMBO', '연환전신장', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (337, 'ITM_TOMAHAWK', 'Throw Tomahawk', 'Etc', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (421, 'TK_JUMPKICK', '날라차기', 'Taekwon', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (526, 'NJ_ZENYNAGE', '돈 던지기', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (527, 'NJ_TATAMIGAESHI', '다다미 뒤집기', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (528, 'NJ_KASUMIKIRI', '안개 베기', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (529, 'NJ_SHADOWJUMP', '그림자 도약', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (530, 'NJ_KIRIKAGE', '그림자 베기', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (531, 'NJ_UTSUSEMI', '매미허물 벗기', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (534, 'NJ_KOUENKA', '홍염화', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (535, 'NJ_KAENSIN', '화염진', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (536, 'NJ_BAKUENRYU', '폭염룡', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (537, 'NJ_HYOUSENSOU', '빙섬창', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (539, 'NJ_HYOUSYOURAKU', '빙정락', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (540, 'NJ_HUUJIN', '풍인', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (541, 'NJ_RAIGEKISAI', '뇌격쇄', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (542, 'NJ_KAMAITACHI', '삭풍 - 카마이타치', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (1001, 'KN_CHARGEATK', '챠지 어택', 'Swordman', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (1004, 'AS_VENOMKNIFE', '베넘 나이프', 'Thief', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (1006, 'WZ_SIGHTBLASTER', '사이트 블래스터', 'Mage', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (1009, 'HT_PHANTASMIC', '판타즈믹 애로우', 'Archer', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (1015, 'MO_KITRANSLATION', '진기주입', 'Acolyte', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2002, 'RK_SONICWAVE', '소닉 웨이브', 'Swordman', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2005, 'RK_WINDCUTTER', '윈드 커터', 'Swordman', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2006, 'RK_IGNITIONBREAK', '이그니션 브레이크', 'Swordman', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2202, 'WL_SOULEXPANSION', '소울 익스펜션', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2203, 'WL_FROSTMISTY', '프로스트 미스티', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2204, 'WL_JACKFROST', '잭 프로스트', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2210, 'WL_DRAINLIFE', '드레인 라이프', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2211, 'WL_CRIMSONROCK', '크림즌 록', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2212, 'WL_HELLINFERNO', '헬 인페르노', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2213, 'WL_COMET', '커미트', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2214, 'WL_CHAINLIGHTNING', '체인 라이트닝', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2215, 'WL_CHAINLIGHTNING_ATK', 'Chain Lightning Attack', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2216, 'WL_EARTHSTRAIN', '어스 스트레인', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2217, 'WL_TETRAVORTEX', '테트라 볼텍스', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2218, 'WL_TETRAVORTEX_FIRE', 'Tetra Vortex Fire', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2219, 'WL_TETRAVORTEX_WATER', 'Tetra Vortex Water', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2220, 'WL_TETRAVORTEX_WIND', 'Tetra Vortex Wind', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2221, 'WL_TETRAVORTEX_GROUND', 'Tetra Vortex Earth', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2222, 'WL_SUMMONFB', '서몬 파이어 볼', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2223, 'WL_SUMMONBL', '서몬 볼 라이트닝', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2224, 'WL_SUMMONWB', '서몬 워터 볼', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2225, 'WL_SUMMON_ATK_FIRE', 'Summon Attack Fire', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2226, 'WL_SUMMON_ATK_WIND', 'Summon Attack Wind', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2227, 'WL_SUMMON_ATK_WATER', 'Summon Attack Water', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2228, 'WL_SUMMON_ATK_GROUND', 'Summon Attack Earth', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2229, 'WL_SUMMONSTONE', '서몬 스톤', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2022, 'GC_CROSSIMPACT', '크로스 임팩트', 'Thief', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2023, 'GC_DARKILLUSION', '다크 일루젼', 'Thief', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2034, 'GC_PHANTOMMENACE', '팬텀 메나스', 'Thief', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2038, 'AB_JUDEX', '쥬덱스', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2040, 'AB_ADORAMUS', '아도라무스', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2050, 'AB_RENOVATIO', '레노바티오', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2051, 'AB_HIGHNESSHEAL', '하이네스 힐', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2054, 'AB_DUPLELIGHT', '듀플레 라이트', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2055, 'AB_DUPLELIGHT_MELEE', 'Duple Light Melee', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2056, 'AB_DUPLELIGHT_MAGIC', 'Duple Light Magic', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2233, 'RA_ARROWSTORM', '애로우 스톰', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2236, 'RA_AIMEDBOLT', '에임드 볼트', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2239, 'RA_CLUSTERBOMB', '클러스터 봄 폭탄)', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2253, 'RA_FIRINGTRAP', '파이어링 트랩', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2254, 'RA_ICEBOUNDTRAP', '아이스바운드 트랩', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2284, 'SC_FATALMENACE', '페이탈 메나스', 'Thief', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2288, 'SC_TRIANGLESHOT', '트라이앵글 샷', 'Thief', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2304, 'SC_FEINTBOMB', '페인트 봄', 'Thief', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2310, 'LG_SHIELDPRESS', '쉴드 프레스', 'Swordman', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2316, 'LG_EXEEDBREAK', '익시드 브레이크', 'Swordman', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2320, 'LG_MOONSLASHER', '문 슬래셔', 'Swordman', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2323, 'LG_EARTHDRIVE', '어스 드라이브', 'Swordman', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2519, 'LG_OVERBRAND_BRANDISH', 'Overbrand Brandish', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2520, 'LG_OVERBRAND_PLUSATK', 'Overbrand Plus Attack', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2326, 'SR_DRAGONCOMBO', '쌍룡각', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2327, 'SR_SKYNETBLOW', '천라지망', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2328, 'SR_EARTHSHAKER', '지뢰진', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2330, 'SR_TIGERCANNON', '호포', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2332, 'SR_RAMPAGEBLASTER', '폭기산탄', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2336, 'SR_KNUCKLEARROW', '수라신탄', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2337, 'SR_WINDMILL', '선풍퇴', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2343, 'SR_GATEOFHELL', '나찰파황격', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2344, 'SR_GENTLETOUCH_QUIET', '점혈 - 묵', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2517, 'SR_HOWLINGOFLION', '사자후', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2518, 'SR_RIDEINLIGHTNING', '뇌광탄', 'Acolyte', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2413, 'WM_METALICSOUND', '메탈릭 사운드', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2414, 'WM_REVERBERATION', '진동 잔향', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2415, 'WM_REVERBERATION_MELEE', 'Reverberation Melee', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2416, 'WM_REVERBERATION_MAGIC', 'Reverberation Magic', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2418, 'WM_SEVERE_RAINSTORM', '서비어 레인스톰', 'Archer', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2516, 'WM_SEVERE_RAINSTORM_MELEE', 'Severe Rainstorm Melee', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2443, 'SO_FIREWALK', '파이어 워크', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2444, 'SO_ELECTRICWALK', '일렉트릭 워크', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2446, 'SO_EARTHGRAVE', '어스 그레이브', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2447, 'SO_DIAMONDDUST', '다이아몬드 더스트', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2448, 'SO_POISON_BUSTER', '포이즌 버스터', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2449, 'SO_PSYCHIC_WAVE', '사이킥 웨이브', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2450, 'SO_CLOUD_KILL', '클라우드 킬', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2454, 'SO_VARETYR_SPEAR', '바레티르 스피어', 'Mage', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2479, 'GN_THORNS_TRAP', '가시나무 덫', 'Merchant', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2480, 'GN_BLOOD_SUCKER', '블러드 서커', 'Merchant', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2481, 'GN_SPORE_EXPLOSION', '스포어 익스플로젼', 'Merchant', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2482, 'GN_WALLOFTHORN', '가시나무의 벽', 'Merchant', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2483, 'GN_CRAZYWEED', '크레이지 위드', 'Merchant', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2484, 'GN_CRAZYWEED_ATK', 'Crazy Weed Attack', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2490, 'GN_HELLS_PLANT', '헬즈 플랜트', 'Merchant', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (2491, 'GN_HELLS_PLANT_ATK', 'Hell''s Plant Attack', 'Etc', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (3008, 'KO_MUCHANAGE', '마구 던지기', 'Ninja', 1, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (5001, 'GC_DARKCROW', '검은 손톱', 'Thief', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (5003, 'GN_ILLUSIONDOPING', '환각 도핑', 'Merchant', 0, 1);
INSERT INTO skill_copyable (skill_id, skill_code, skill_name, job_group, plagiarism, reproduce) VALUES (5006, 'NC_MAGMA_ERUPTION', '용암 분출', 'Merchant', 0, 1);