// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

BUILDIN_DEF(need_register_equipment_build,"iss"),
BUILDIN_DEF(need_get_equipment_build_count,""),
BUILDIN_DEF(need_show_last_equipment_build,""),
BUILDIN_DEF(need_equipment_build_category_name,"i"),
BUILDIN_DEF(need_equipment_build_status_name,"i"),
BUILDIN_DEF(need_equipment_build_is_admin,""),
BUILDIN_DEF(need_get_admin_equipment_build_list,"ii"),
BUILDIN_DEF(need_search_admin_equipment_builds,"isi"),
BUILDIN_DEF(need_get_public_equipment_build_jobs,"i"),
BUILDIN_DEF(need_get_public_equipment_build_list,"iiii"),
BUILDIN_DEF(need_get_my_equipment_build_list,"i"),
BUILDIN_DEF(need_show_admin_equipment_build,"i"),
BUILDIN_DEF(need_show_public_equipment_build,"i"),
BUILDIN_DEF(need_show_my_equipment_build,"i"),
BUILDIN_DEF(need_review_equipment_build,"iis"),
BUILDIN_DEF(need_approve_equipment_build,"iii"),
BUILDIN_DEF(need_cancel_equipment_build,"i"),
BUILDIN_DEF(need_toggle_equipment_build_like,"i"),
BUILDIN_DEF(need_get_my_equipment_build_reward_list,"i"),
BUILDIN_DEF(need_show_my_equipment_build_reward,"i"),
BUILDIN_DEF(need_claim_equipment_build_reward,"i"),

BUILDIN_DEF(clearmapskillunits, "s"),

BUILDIN_DEF(instance_ip_complete,"i"),
BUILDIN_DEF(instance_ip_reward_remaining,"?"),
BUILDIN_DEF(instance_ip_reward_limit,"?"),

BUILDIN_DEF(skillselectmenu,"*"),
BUILDIN_DEF(skillselectmenuarray,"r"),
BUILDIN_DEF(getskillname,"v"),
BUILDIN_DEF(getskilldesc,"v"),
BUILDIN_DEF(getplagiarizedskill,"?"),
BUILDIN_DEF(getplagiarizedskilllv,"?"),
BUILDIN_DEF(getskillid,"s"),
BUILDIN_DEF(storagegetitem, "ii"),
