//--------------------------------------------------------------
// rAthena Battle Configuration File
// Originally Translated by Peter Kieser <pfak@telus.net>
// Made in to plainer English by Ancyker
//--------------------------------------------------------------
// Note 1: Value is a config switch (on/off, yes/no or 1/0)
// Note 2: Value is in percents (100 means 100%)
// Note 3: Value is a bit field. If no description is given,
//         assume unit types (1: Pc, 2: Mob, 4: Pet, 8: Homun)
//--------------------------------------------------------------

// 활성화된 인스턴스가 있을 경우, 파티/길드/클랜 탈퇴를 막을 것인가?
// 기본값: yes (공식 서버 기준)
instance_block_leave: no

// 활성화된 인스턴스가 있을 경우, 파티/길드의 리더 변경을 막을 것인가?
// 기본값: yes (공식 서버 기준)
instance_block_leaderchange: yes

// 활성화된 인스턴스가 있을 경우, 파티/길드 초대를 막을 것인가?
// 이 설정은 실행 중인 인스턴스가 있는 파티/길드/클랜에 가입하는 것도 막는다.
// 기본값: yes (공식 서버 기준)
instance_block_invite: yes

// 활성화된 인스턴스가 있을 경우, 파티/길드/클랜에서 추방하는 것을 막을 것인가?
// 기본값: yes (공식 서버 기준)
instance_block_expulsion: yes