CREATE TABLE IF NOT EXISTS `need_autopot_preset` (
  `account_id` INT UNSIGNED NOT NULL,
  `slot` TINYINT UNSIGNED NOT NULL,
  `name` VARCHAR(24) NOT NULL DEFAULT '',
  `hp_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `hp_item_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `hp_percent` TINYINT UNSIGNED NOT NULL DEFAULT 90,
  `sp_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `sp_item_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `sp_percent` TINYINT UNSIGNED NOT NULL DEFAULT 50,
  `interval_ms` SMALLINT UNSIGNED NOT NULL DEFAULT 500,
  PRIMARY KEY (`account_id`, `slot`)
) ENGINE=InnoDB;
