
npc: npc/NEED/buff.txt
npc: npc/NEED/chobozone.txt
npc: npc/NEED/Costume.txt
npc: npc/NEED/FirstGuide.txt
//npc: npc/NEED/tabyu.txt
npc: npc/NEED/Storage_Command.txt
npc: npc/NEED/kafra.txt
npc: npc/NEED/guide.txt
npc: npc/NEED/reborn.txt
npc: npc/NEED/shop.txt
//npc: npc/NEED/lhz_dun_n_gate.txt
npc: npc/NEED/dojak.txt
npc: npc/NEED/cash.txt
npc: npc/NEED/test_item.txt
npc: npc/NEED/NEED_Function.txt
npc: npc/NEED/world_drop_by_lv.txt
npc: npc/NEED/captcha.txt
npc: npc/NEED/need_grace.txt

// ------------------------ Instances ---------------------------
npc: npc/NEED/instances/SealedShrine.txt
npc: npc/NEED/instances/EndlessTower.txt
npc: npc/NEED/instances/NydhoggsNest.txt
npc: npc/NEED/instances/BakonawaLake.txt
npc: npc/NEED/instances/BangungotHospital.txt
npc: npc/NEED/instances/BuwayaCave.txt
npc: npc/NEED/instances/Old_Glast_Heim.txt
npc: npc/NEED/instances/WolfchevLaboratory.txt

//npc: npc/NEED/instances/AirshipAssault.txt
//npc: npc/NEED/instances/CentralLaboratory.txt
//npc: npc/NEED/instances/CharlestonCrisis.txt
//npc: npc/NEED/instances/CorOperation.txt
//npc: npc/NEED/instances/DeepForest.txt
//npc: npc/NEED/instances/DevilTower.txt
//npc: npc/NEED/instances/EclageInterior.txt
//npc: npc/NEED/instances/EddaHalfMoonInTheDaylight.txt
//npc: npc/NEED/instances/FacewormsNest.txt
//npc: npc/NEED/instances/FridayDungeon.txt
//npc: npc/NEED/instances/GhostPalace.txt
//npc: npc/NEED/instances/HazyForest.txt
//npc: npc/NEED/instances/HorrorToyFactory.txt
//npc: npc/NEED/instances/HeartHunterWarBase.txt
//npc: npc/NEED/instances/HiddenGarden.txt
//npc: npc/NEED/instances/InfiniteSpace.txt
//npc: npc/NEED/instances/IsleOfBios.txt
//npc: npc/NEED/instances/LastRoom.txt
//npc: npc/NEED/instances/LostFarm.txt
//npc: npc/NEED/instances/MalangdoCulvert.txt
//npc: npc/NEED/instances/MazeofOz.txt
//npc: npc/NEED/instances/MorseCave.txt
//npc: npc/NEED/instances/NightmarishJitterbug.txt
//npc: npc/NEED/instances/OsOccupation.txt
//npc: npc/NEED/instances/PoringVillage.txt
//npc: npc/NEED/instances/Regenschirm.txt
//npc: npc/NEED/instances/RitualOfBlessing.txt
//npc: npc/NEED/instances/RoomOfConsciousness.txt
//npc: npc/NEED/instances/SarahAndFenrir.txt
//npc: npc/NEED/instances/SaraMemory.txt
//npc: npc/NEED/instances/SealedOs.txt
//npc: npc/NEED/instances/SkyFortress.txt
//npc: npc/NEED/instances/TempleOfDemonGod.txt
//npc: npc/NEED/instances/ThorGunsuBase.txt
//npc: npc/NEED/instances/TwilightGarden.txt
//npc: npc/NEED/instances/VillaofDeception.txt
//npc: npc/NEED/instances/VillaofHighPriest.txt
//npc: npc/NEED/instances/WaterGarden.txt
//npc: npc/NEED/instances/WeekendDungeon.txt
//npc: npc/NEED/instances/WernerLaboratoryCentralRoom.txt
//npc: npc/NEED/instances/Wolves.txt