// --------------------------------------------------------------
// -                        Core Scripts                        -
// --------------------------------------------------------------

// --------------------- Battle Grounds -------------------------
// - Flavius ----------------------------------------------------
npc: npc/battleground/flavius/flavius_enter.txt
npc: npc/battleground/flavius/flavius01.txt
// - Kreiger Von Midgard ----------------------------------------
npc: npc/battleground/kvm/kvm_enter.txt
npc: npc/battleground/kvm/kvm_item_pay.txt
npc: npc/battleground/kvm/kvm01.txt
// - Tierra Gorge -----------------------------------------------
npc: npc/battleground/tierra/tierra_enter.txt
npc: npc/battleground/tierra/tierra01.txt
// --------------------------------------------------------------
npc: npc/battleground/bg_common.txt

// --------------------------- Cities ---------------------------
npc: npc/cities/payon.txt

// --------------------------------------------------------------
//npc: npc/events/bossnia.txt
// - Official indian Ro Event Children Week

// -------------------------- Merchant --------------------------
npc: npc/merchants/enchan_arm.txt
npc: npc/merchants/refine.txt

// --------------------------------------------------------------
npc: npc/other/gm_npcs.txt
npc: npc/other/gympass.txt
npc: npc/other/marriage.txt

//npc: npc/other/hugel_bingo.txt
//npc: npc/other/poring_war.txt
//npc: npc/other/turbo_track.txt

// --------------------------- Quests ---------------------------
// - Quests-Tutorials for basic classes (1st class quests) ------
npc: npc/quests/okolnir.txt
// - The God Item Quest -----------------------------------------
// - Controller file, allow GMs to change variables.
npc: npc/quests/seals/god_global.txt
npc: npc/quests/seals/brisingamen_seal.txt
npc: npc/quests/seals/god_weapon_creation.txt
npc: npc/quests/seals/megingard_seal.txt
npc: npc/quests/seals/mjolnir_seal.txt
npc: npc/quests/seals/sleipnir_seal.txt
// - Seal status board.
npc: npc/quests/seals/seal_status.txt
// --------------------------------------------------------------
// - Wandering Minstrel Quest
npc: npc/quests/lvl4_weapon_quest.txt
//npc: npc/quests/quests_13_1.txt
//npc: npc/quests/quests_13_2.txt
//npc: npc/quests/quests_airship.txt
//npc: npc/quests/quests_alberta.txt
//npc: npc/quests/quests_aldebaran.txt
//npc: npc/quests/quests_amatsu.txt
//npc: npc/quests/quests_ayothaya.txt
//npc: npc/quests/quests_brasilis.txt
//npc: npc/quests/quests_comodo.txt
//npc: npc/quests/quests_ein.txt
//npc: npc/quests/quests_geffen.txt
//npc: npc/quests/quests_gonryun.txt
//npc: npc/quests/quests_hugel.txt
//npc: npc/quests/quests_izlude.txt
//npc: npc/quests/quests_juperos.txt
//npc: npc/quests/quests_lighthalzen.txt
//npc: npc/quests/quests_louyang.txt
//npc: npc/quests/quests_lutie.txt
//npc: npc/quests/quests_morocc.txt
//npc: npc/quests/quests_moscovia.txt
//npc: npc/quests/quests_nameless.txt
//npc: npc/quests/quests_niflheim.txt
//npc: npc/quests/quests_payon.txt
//npc: npc/quests/quests_prontera.txt
//npc: npc/quests/quests_rachel.txt
//npc: npc/quests/quests_umbala.txt
//npc: npc/quests/quests_veins.txt
//npc: npc/quests/quests_yuno.txt
//npc: npc/quests/thana_quest.txt
// - The Sign Quest
//   Be sure that the time zone set corresponds with the server's.
//   For more info, read the comments in npc/quests/the_sign_quest.txt
//npc: npc/quests/the_sign_quest.txt