// --------------------------------------------------------------
// -                       Custom Scripts                       -
// --------------------------------------------------------------
//      All the custom scripts, remove the '//' to enable...     
//      Place your scripts here!

// ----------------------- Basic Scripts -----------------------
npc: npc/custom/warper.txt
npc: npc/custom/jobmaster.txt
//npc: npc/custom/woe_controller.txt

// ----------------------- Other Scripts -----------------------
// -- Private MVP & Branch Room
//npc: npc/custom/etc/penal_servitude.txt
//npc: npc/custom/etc/blackjack.txt
npc: npc/custom/etc/autopot.txt

// ----------------------- Quest Scripts -----------------------
// -- Dynamic Quest Scripts
//npc: npc/custom/quests/hunting_missions.txt
//npc: npc/custom/quests/quest_shop.txt
//npc: npc/custom/quests/questboard.txt
// -- Treasure Hunters Guild Quests (40 Quests + Special Guild Shop)
//npc: npc/custom/quests/thq/THQS_ChattingNPC.txt
//npc: npc/custom/quests/thq/THQS_GuildNPC.txt
//npc: npc/custom/quests/thq/THQS_QuestNPC.txt
//npc: npc/custom/quests/thq/THQS_Quests.txt
//npc: npc/custom/quests/thq/THQS_TTShop.txt

// ----------------------- Event Scripts -----------------------
// -- Mini-Game Events
//npc: npc/custom/events/devil_square.txt
//npc: npc/custom/events/disguise.txt
//npc: npc/custom/events/mvp_ladder.txt

// -------------------- Battleround Scripts --------------------
// -- Custom Battleground Scripts
//npc: npc/custom/battleground/bg_emp.txt
//npc: npc/custom/battleground/bg_pvp.txt